name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20, 22, 24 ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install deps
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Type check
      run: npm run typecheck

    - name: Run tests
      run: npm run test:coverage

    - name: Build project
      run: npm run build
