name: Publish Github release

on:
  schedule:
  - cron: '33 9 * * 1' # Every Monday at 9:00 AM UTC
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  send-newsletter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install deps
      run: npm ci

    - name: Copy .env file
      run: cp .env.example .env

    - name: Publish Github release
      run: npm run start
      env:
        GITHUB_RELEASES_ENABLED: true
        GITHUB_RELEASES_REPO: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
