name: Send newsletter

on:
  schedule:
  - cron: '0 9 * * 1' # Every Monday at 9:00 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  send-newsletter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install deps
      run: npm ci

    - name: Copy .env file
      run: cp .env.example .env

    - name: Send newsletter
      run: npm run start
      env:
        RESEND_ENABLED: true
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        RESEND_AUDIENCE_ID: ${{ secrets.RESEND_AUDIENCE_ID }}
        RESEND_FROM: ${{ secrets.RESEND_FROM }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
